# Generated by Django 3.1.3 on 2020-12-04 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Workspace', max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspace', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='workspace', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='work_board', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='collab.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('work_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_group', to='collab.workboard')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Undefined task', max_length=255)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('on-going', 'On progress'), ('stuck', 'Stuck'), ('done', 'Finished'), ('queue', 'Queue')], default='queue', max_length=255)),
                ('due_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('people', models.ManyToManyField(related_name='task', to=settings.AUTH_USER_MODEL)),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='collab.taskgroup')),
            ],
        ),
    ]
