# Generated by Django 3.1.3 on 2020-12-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workboard',
            name='title',
            field=models.CharField(default='Work Board', max_length=255),
        ),
    ]
