# Generated by Django 3.1.3 on 2020-12-06 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0002_workboard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workboard',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='work_board', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='workspace', to=settings.AUTH_USER_MODEL),
        ),
    ]
