# Generated by Django 3.1.3 on 2020-12-06 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0003_auto_20201206_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspace', to=settings.AUTH_USER_MODEL),
        ),
    ]
